// MT6789 GPU UV+OC via working-table patch (option B).
// Variants 1200-1900MHz (gen_opp.py, V = F*0.682 snapped 625), UV -1250 mid-stack.
// Method: modify existing entries, OPP_NUM stays 45. No hot-path hooks.
// Call the wrapper's official getters, patch on init (GPU idle), restore on exit.
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/errno.h>
#include <linux/string.h>

#define OPP_NUM 45
#define ENTRY_U32 6
#define UV_OFFSET 1250 // -12.5mV mid-stack, hardcoded (no module_param)

// GED BSS offsets (ged.ko from vendor_dlkm, Wild 6.12.38): g_working_table
// is a boot-time kmalloc copy of the working table that ged_get_freq_by_idx
// (hence /sys/kernel/ged/hal/current_freqency) reads instead of the live
// table. Entries are validated against the stock backup before patching, so
// a ged.ko update that moves these offsets fails safe (GED sync skipped,
// working patch kept).
#define GED_BSS_WORKING_OFF 0x9c80
#define GED_BSS_TOP_OFF 0x9c88
// Signed table (g_gpu in mtk_gpufreq_mt6789.ko, .bss+0x0): golden table that
// __gpufreq_freq_scale_gpu scans live for posdiv selection, and what
// /proc/gpufreqv2/gpu_signed_opp_table displays. Same validate pattern;
// gpufreq_get_signed_table is NOT exported so direct import fails.
// NOTE: GKI trims filp_open and protects kernel_read on this kernel, so the
// BSS bases cannot be resolved from inside the module. Pass them from the
// root shell, e.g.:
//   insmod gpu_uvoc.ko ged_bss=$(cat /sys/module/ged/sections/.bss) \
//     mt6789_bss=$(cat /sys/module/mtk_gpufreq_mt6789/sections/.bss)
static unsigned long ged_bss;
module_param(ged_bss, ulong, 0444);
MODULE_PARM_DESC(ged_bss, "runtime .bss base of ged.ko (0 = skip GED sync)");
static unsigned long mt6789_bss;
module_param(mt6789_bss, ulong, 0444);
MODULE_PARM_DESC(mt6789_bss, "runtime .bss base of mtk_gpufreq_mt6789.ko (0 = skip signed sync)");
#define SIGNED_BSS_GPU_OFF 0x0

// Official getters from mtk_gpufreq_wrapper_legacy.ko (EXPORT_SYMBOL, no crc
// under GKI basic-modversions so version-independent). type 1 = GPU.
extern void *gpufreq_get_working_table(unsigned int type);
extern unsigned int gpufreq_get_opp_num(unsigned int type);

struct opp { u32 freq, volt, vsram, posdiv, margin, power; };

// Per-variant 45-entry OPP table, generated by tools/gen_opp.py -> src/opp_table.h:
// 50MHz/1875uV staircase from Fmax down to 1100, live-UV tail below.
// power is ignored here (recomputed via dyn_power at init).
#include "opp_table.h"

static struct opp opp_backup[OPP_NUM];
static void *tbl_addr;
static bool patched;

// GED-side copies (kmalloc'd at ged_gpufreq_init, 45 x 6 u32 each).
static struct opp ged_backup[OPP_NUM];
static struct opp ged_top_backup[OPP_NUM];
static void *ged_addr;
static void *ged_top_addr;
static bool ged_patched;

// Signed table (in-place AVS'd g_default_gpu, 45 x 6 u32).
static struct opp signed_backup[OPP_NUM];
static void *signed_addr;
static bool signed_patched;

static bool uvoc_in_range(u32 f, u32 v, u32 s)
{
  if (f < 187500 || f > 1900000)
    return false;
  if (v < 50000 || v > 129696) // regulator max 0x13BB45 uV / 10, abort above
    return false;
  if (s < 75000 || s > 129696)
    return false;
  return true;
}

static u32 dyn_power(u32 f, u32 v)
{
  u64 a = (u64)f * 100 / 1100000;
  u64 b = (u64)v * 100 / 85000;
  return (u32)(a * b * b * 0x3d1 / 1000000);
}

static void ged_sync_tables(void);
static void signed_sync_table(void);

static int __init uvoc_init(void)
{
  u32 *t;
  unsigned int n;
  int i;

  n = gpufreq_get_opp_num(1);
  if (n != OPP_NUM) {
    pr_err("[gpu-uvoc] OPP_NUM=%u, expected 45, abort (PRI: segment/AVS mismatch)\n", n);
    return -EINVAL;
  }
  t = (u32 *)gpufreq_get_working_table(1);
  if (!t) {
    pr_err("[gpu-uvoc] working table null\n");
    return -ENOENT;
  }
  tbl_addr = t;
  // Fail-safe: refuse foreign or already-patched tables instead of
  // compounding. Stock freq anchors never move with AVS/aging (golden:
  // idx0 1100000, idx44 390000); vsram floor is 75000 everywhere. A later
  // re-probe of mtk_gpufreq reads back the regulators and aborts (panics)
  // on vsram below the floor, so never let such state through here.
  if (t[0] != 1100000 || t[(OPP_NUM - 1) * ENTRY_U32] != 390000) {
    pr_err("[gpu-uvoc] table anchors idx0=%u idx44=%u, want 1100000/390000 (already patched?), abort\n",
           t[0], t[(OPP_NUM - 1) * ENTRY_U32]);
    return -EINVAL;
  }
  for (i = 0; i < OPP_NUM; i++) {
    u32 s = t[i * ENTRY_U32 + 2];
    if (s < 75000 || s > 129696) {
      pr_err("[gpu-uvoc] live vsram idx%d=%u outside [75000,129696], abort\n", i, s);
      return -EINVAL;
    }
  }
  for (i = 0; i < OPP_NUM; i++) { // manual backup, avoid importing memcpy
    int j;
    for (j = 0; j < ENTRY_U32; j++)
      ((u32 *)opp_backup)[i * ENTRY_U32 + j] = t[i * ENTRY_U32 + j];
  }

  // build idx HEAD_NUM+ from the live table - UV_OFFSET (follows AVS/aging).
  // idx <HEAD_NUM = fixed staircase (no live reference above 1100).
  for (i = HEAD_NUM; i < OPP_NUM; i++) {
    u32 f = t[i * ENTRY_U32 + 0];
    u32 v = t[i * ENTRY_U32 + 1];
    u32 s = t[i * ENTRY_U32 + 2];
    u32 nv = (v > (u32)UV_OFFSET) ? v - UV_OFFSET : v;
    u32 ns = (s > 75000 + (u32)UV_OFFSET) ? s - UV_OFFSET : s;
    if (nv < 50000)
      nv = 50000;
    if (ns < 75000)
      ns = 75000;
    opp_new[i].freq = f;
    opp_new[i].volt = nv;
    opp_new[i].vsram = ns;
    opp_new[i].posdiv = t[i * ENTRY_U32 + 3];
    opp_new[i].margin = t[i * ENTRY_U32 + 4];
    opp_new[i].power = dyn_power(f, nv);
  }
  opp_new[0].power = dyn_power(opp_new[0].freq, opp_new[0].volt);
  opp_new[1].power = dyn_power(opp_new[1].freq, opp_new[1].volt);
  opp_new[2].power = dyn_power(opp_new[2].freq, opp_new[2].volt);

  for (i = 0; i < OPP_NUM; i++) {
    if (!uvoc_in_range(opp_new[i].freq, opp_new[i].volt, opp_new[i].vsram)) {
      pr_err("[gpu-uvoc] entry %d out of range f=%u v=%u s=%u, abort\n",
             i, opp_new[i].freq, opp_new[i].volt, opp_new[i].vsram);
      return -EINVAL;
    }
    if (abs((int)opp_new[i].volt - (int)opp_new[(i > 0) ? i - 1 : 0].volt) > HEAD_VGUARD && i > 0) {
      pr_err("[gpu-uvoc] volt step idx%d >%d, abort\n", i, HEAD_VGUARD);
      return -EINVAL;
    }
  }

  // apply: 6 u32 per entry. posdiv/margin follow the header (staircase posdiv 1,
  // tail = live values, so no-op below). Small race window; patch while idle.
  for (i = 0; i < OPP_NUM; i++) {
    t[i * ENTRY_U32 + 0] = opp_new[i].freq;
    t[i * ENTRY_U32 + 1] = opp_new[i].volt;
    t[i * ENTRY_U32 + 2] = opp_new[i].vsram;
    t[i * ENTRY_U32 + 3] = opp_new[i].posdiv;
    t[i * ENTRY_U32 + 4] = opp_new[i].margin;
    t[i * ENTRY_U32 + 5] = opp_new[i].power;
  }
  patched = true;
  pr_info("[gpu-uvoc] patched: idx0 %u/%u idx1 %u/%u, UV -%d mid-stack\n",
          opp_new[0].freq, opp_new[0].volt, opp_new[1].freq, opp_new[1].volt, UV_OFFSET);

  // GED HAL (/sys/kernel/ged/hal/current_freqency) translates the live idx
  // through its own boot-time table copies, so mirror the same entries there.
  // Validation first: both copies must still hold the stock freqs.
  ged_sync_tables();
  // Signed table: live posdiv source for freq_scale + procfs display.
  signed_sync_table();
  pr_info("[gpu-uvoc] verify: cat /proc/gpufreqv2/gpu_working_opp_table; echo 0 > .../fix_target_opp_index then cat /sys/kernel/ged/hal/current_freqency\n");
  return 0;
}

// Read a module's runtime section base, e.g. /sys/module/ged/sections/.bss.
static unsigned long ged_bss_live;
static unsigned long mt6789_bss_live;

static void ged_sync_tables(void)
{
  u32 *g, *gtop;
  int i, j;

  if (!ged_bss) {
    pr_info("[gpu-uvoc] GED sync skipped: pass ged_bss=$(cat /sys/module/ged/sections/.bss)\n");
    return;
  }
  ged_bss_live = ged_bss;
  g = *(u32 **)(ged_bss_live + GED_BSS_WORKING_OFF);
  gtop = *(u32 **)(ged_bss_live + GED_BSS_TOP_OFF);
  if (!g || !gtop) {
    pr_info("[gpu-uvoc] GED sync skipped: null table ptr\n");
    return;
  }
  for (i = 0; i < OPP_NUM; i++) { // must still be the stock table
    if (g[i * ENTRY_U32 + 0] != ((u32 *)opp_backup)[i * ENTRY_U32 + 0] ||
        gtop[i * ENTRY_U32 + 0] != ((u32 *)opp_backup)[i * ENTRY_U32 + 0]) {
      pr_err("[gpu-uvoc] GED sync aborted: entry %d mismatch (ged.ko layout moved?), working patch kept\n", i);
      return;
    }
  }
  ged_addr = g;
  ged_top_addr = gtop;
  for (i = 0; i < OPP_NUM; i++) {
    for (j = 0; j < ENTRY_U32; j++) {
      ((u32 *)ged_backup)[i * ENTRY_U32 + j] = g[i * ENTRY_U32 + j];
      ((u32 *)ged_top_backup)[i * ENTRY_U32 + j] = gtop[i * ENTRY_U32 + j];
      g[i * ENTRY_U32 + j] = ((u32 *)opp_new)[i * ENTRY_U32 + j];
      gtop[i * ENTRY_U32 + j] = ((u32 *)opp_new)[i * ENTRY_U32 + j];
    }
  }
  ged_patched = true;
  pr_info("[gpu-uvoc] GED tables synced (idx0 %u)\n", opp_new[0].freq);
}

static void signed_sync_table(void)
{
  u32 *s;
  int i, j;

  if (!mt6789_bss) {
    pr_info("[gpu-uvoc] signed sync skipped: pass mt6789_bss=$(cat /sys/module/mtk_gpufreq_mt6789/sections/.bss)\n");
    return;
  }
  mt6789_bss_live = mt6789_bss;
  s = *(u32 **)(mt6789_bss_live + SIGNED_BSS_GPU_OFF);
  if (!s) {
    pr_info("[gpu-uvoc] signed sync skipped: null table ptr\n");
    return;
  }
  for (i = 0; i < OPP_NUM; i++) { // must still be the stock table
    if (s[i * ENTRY_U32 + 0] != ((u32 *)opp_backup)[i * ENTRY_U32 + 0]) {
      pr_err("[gpu-uvoc] signed sync aborted: entry %d mismatch (mtk_gpufreq_mt6789.ko layout moved?), working+GED patch kept\n", i);
      return;
    }
  }
  signed_addr = s;
  for (i = 0; i < OPP_NUM; i++) {
    for (j = 0; j < ENTRY_U32; j++) {
      ((u32 *)signed_backup)[i * ENTRY_U32 + j] = s[i * ENTRY_U32 + j];
      s[i * ENTRY_U32 + j] = ((u32 *)opp_new)[i * ENTRY_U32 + j];
    }
  }
  signed_patched = true;
  pr_info("[gpu-uvoc] signed table synced (idx0 %u)\n", opp_new[0].freq);
}

static void __exit uvoc_exit(void)
{
  int i;
  if (patched && tbl_addr) {
    u32 *t = (u32 *)tbl_addr; // manual restore
    for (i = 0; i < OPP_NUM; i++) {
      int j;
      for (j = 0; j < ENTRY_U32; j++)
        t[i * ENTRY_U32 + j] = ((u32 *)opp_backup)[i * ENTRY_U32 + j];
    }
    pr_info("[gpu-uvoc] working table restored\n");
  }
  if (ged_patched) {
    int j;
    u32 *g = (u32 *)ged_addr; // manual restore
    u32 *gtop = (u32 *)ged_top_addr;
    for (i = 0; i < OPP_NUM; i++) {
      for (j = 0; j < ENTRY_U32; j++) {
        g[i * ENTRY_U32 + j] = ((u32 *)ged_backup)[i * ENTRY_U32 + j];
        gtop[i * ENTRY_U32 + j] = ((u32 *)ged_top_backup)[i * ENTRY_U32 + j];
      }
    }
    pr_info("[gpu-uvoc] GED tables restored\n");
  }
  if (signed_patched) {
    int j;
    u32 *s = (u32 *)signed_addr; // manual restore
    for (i = 0; i < OPP_NUM; i++) {
      for (j = 0; j < ENTRY_U32; j++)
        s[i * ENTRY_U32 + j] = ((u32 *)signed_backup)[i * ENTRY_U32 + j];
    }
    pr_info("[gpu-uvoc] signed table restored\n");
  }
}

module_init(uvoc_init);
module_exit(uvoc_exit);
MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("MT6789 GPU UV(-12.5mV)+OC working-table patch, variant via opp_table.h");

